import { useEffect, useState } from "react";
import { Eye } from "lucide-react";
import * as XLSX from "xlsx";
import { Alert, Card, DataTable, EmptyState, FilterCard, ModalShell, PageContainer, PageHeader } from "../../components/ui";
import { listMasters } from "../../services/masterService";
import { getCompanyBillingReport, getExecutivePerformanceReport } from "../../services/billingReportService";
import type { CompanyBillingReport, ExecutiveBankRow, ExecutivePerformanceReport } from "../../types/billingReport";

const input="h-10 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-900";
const companyHeaders=["Date","LOS","Bank","Visit Type","Applicant","Address","Dist","City","Mobile Number","Executive","Status","Executive Rate","Company Rate","Payment Status"];
const executiveHeaders=["Executive","Bank / Finance Company","Total Cases/Visits","Pending","Positive","Negative","Executive Rate Total","Action"];
const summaryHeaders=["Executive","Total Visits","Pending","Positive","Negative","Total Payment"];
const detailHeaders=["Date","LOS","Applicant","Address","Mobile","Visit Type","Company","Bank","District","City","Status","Executive Rate"];
const showMoney=(value:string|null,status="MISSING")=>value===null?status:new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(value));
const label=(value:string|null|undefined)=>value?.trim()||"Not available";

export default function BillingReportsPage({kind}:{kind:"company"|"executive"}) {
  const [filters,setFilters]=useState({company_id:"",date_from:"",date_to:"",bank:"",district_id:"",city:"",executive:"",visit_type:"",status:"",payment_status:""});
  const [companies,setCompanies]=useState<{id:number;name:string}[]>([]); const [executives,setExecutives]=useState<{full_name:string}[]>([]); const [districts,setDistricts]=useState<{id:number;name:string}[]>([]);
  const [report,setReport]=useState<CompanyBillingReport|ExecutivePerformanceReport|null>(null); const [selected,setSelected]=useState<ExecutiveBankRow|null>(null);
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [attempted,setAttempted]=useState(false);
  useEffect(()=>{void Promise.all([listMasters("companies",{all:true}),listMasters("executives",{all:true}),listMasters("districts",{all:true})]).then(([c,e,d])=>{setCompanies(c.items);setExecutives(e.items);setDistricts(d.items)}).catch(()=>setError("Unable to load report filters."))},[]);
  const params=()=>Object.fromEntries(Object.entries(filters).filter(([key,value])=>value!==""&&(kind==="company"||!["visit_type","payment_status"].includes(key))));
  const preview=async()=>{setBusy(true);setAttempted(true);setError("");setReport(null);try{setReport(kind==="company"?await getCompanyBillingReport(params()):await getExecutivePerformanceReport(params()))}catch(e){setError((e as {response?:{data?:{detail?:string}}}).response?.data?.detail||"Unable to load report.")}finally{setBusy(false)}};
  const download=()=>{if(!report)return;const wb=XLSX.utils.book_new();if(kind==="company"){const r=report as CompanyBillingReport;XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([companyHeaders,...r.items.map(x=>[x.date,x.los,x.bank,x.visit_type,x.applicant,x.address,x.dist,x.city,x.mobile_number,x.executive,x.status,x.executive_rate??x.executive_rate_status,x.company_rate??x.company_rate_status,x.payment_status])]),"Company Billing");const company=companies.find(x=>String(x.id)===filters.company_id)?.name.replace(/[^a-z0-9]+/gi,"_")||"company";XLSX.writeFile(wb,`company_billing_${company}_${filters.date_from}_to_${filters.date_to}.xlsx`)}else{const r=report as ExecutivePerformanceReport;XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([executiveHeaders.slice(0,-1),...r.items.map(x=>[x.executive,x.bank_finance_company,x.total_cases_visits,x.pending,x.positive,x.negative,x.executive_rate_total??x.rate_status])]),"Executive + Bank Summary");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([summaryHeaders,...r.executive_summary.map(x=>[x.executive,x.total_visits,x.pending,x.positive,x.negative,x.total_payment??x.rate_status])]),"Executive Summary");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([detailHeaders,...r.items.flatMap(group=>group.details.map(x=>[x.date,x.los,x.applicant,x.address,x.mobile,x.visit_type,x.company,x.bank,x.district,x.city,x.status,x.executive_rate??x.executive_rate_status]))]),"Executive Visit Details");XLSX.writeFile(wb,`executive_performance_${filters.date_from}_to_${filters.date_to}.xlsx`)}};
  const set=(key:string,value:string)=>setFilters(x=>({...x,[key]:value})); const totals=report?.totals;
  const cards=kind==="company"?[["Total Visits","total_visits"],["Pending","pending"],["Positive","positive"],["Negative","negative"],["Company Billing Total","company_billing_total","money"],["Executive Payment Total","executive_payment_total","money"],["Paid","paid_total","money"],["Balance","balance_total","money"]]:[["Total Visits","total_visits"],["Pending","pending"],["Positive","positive"],["Negative","negative"],["Executive Rate Total","executive_rate_total","money"]];
  return <PageContainer><PageHeader eyebrow="Billing reports" title={kind==="company"?"Company Billing Export":"Executive Performance Report"} subtitle="Authoritative, permission-scoped visit-level reporting." />
    <FilterCard className="!grid !grid-cols-1 md:!grid-cols-2 xl:!grid-cols-6 [&>div]:contents [&_button]:!h-10 [&_button]:w-full [&_button]:self-auto" onSubmit={e=>{e.preventDefault();void preview()}}><div className="contents">
      {kind==="company"&&<select required aria-label="Company" className={input} value={filters.company_id} onChange={e=>set("company_id",e.target.value)}><option value="">Company (required)</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}
      <input required aria-label="From Date" type="date" className={input} value={filters.date_from} onChange={e=>set("date_from",e.target.value)}/><input required aria-label="To Date" type="date" className={input} value={filters.date_to} onChange={e=>set("date_to",e.target.value)}/>
      {kind==="executive"&&<select aria-label="Company" className={input} value={filters.company_id} onChange={e=>set("company_id",e.target.value)}><option value="">All companies</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}
      <input aria-label="Bank" className={input} placeholder="Bank / Finance Company" value={filters.bank} onChange={e=>set("bank",e.target.value)}/><select aria-label="District" className={input} value={filters.district_id} onChange={e=>set("district_id",e.target.value)}><option value="">All districts</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input aria-label="City" className={input} placeholder="City" value={filters.city} onChange={e=>set("city",e.target.value)}/><select aria-label="Executive" className={input} value={filters.executive} onChange={e=>set("executive",e.target.value)}><option value="">All executives</option>{executives.map(x=><option key={x.full_name}>{x.full_name}</option>)}</select>
      {kind==="company"&&<><select aria-label="Visit Type" className={input} value={filters.visit_type} onChange={e=>set("visit_type",e.target.value)}><option value="">All visit types</option>{["Residence","Office","Permanent","Business","Other"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Payment Status" className={input} value={filters.payment_status} onChange={e=>set("payment_status",e.target.value)}><option value="">All payment states</option>{["Pending","Partially Paid","Paid","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></>}
      <select aria-label="Status" className={input} value={filters.status} onChange={e=>set("status",e.target.value)}><option value="">All statuses</option>{["Pending","Positive","Negative"].map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-4 flex flex-wrap gap-3"><button className="rounded-xl bg-orange-600 px-5 py-2 text-white disabled:opacity-60" disabled={busy}>{busy?"Loading…":"Preview"}</button><button type="button" onClick={download} disabled={!report||busy} className="rounded-xl border px-5 py-2 disabled:opacity-50">Download Excel</button></div></FilterCard>
    {error&&<Alert>{error}</Alert>}{busy&&<Card><div className="space-y-3 animate-pulse" aria-label="Loading report"><div className="h-5 w-48 rounded bg-slate-200"/><div className="h-24 rounded bg-slate-100"/></div></Card>}
    {!busy&&!attempted&&!error&&<Card className="mt-4 grid min-h-[180px] place-items-center"><EmptyState>Select filters and click Preview to load the report.</EmptyState></Card>}
    {report&&<>{report.metadata.limitations.length>0&&<Alert tone={report.metadata.contains_draft?"warning":"info"}>{report.metadata.state} report. {report.metadata.limitations.join(" ")}</Alert>}
      {report.items.length===0?<Card><EmptyState>No report data found for the selected filters.</EmptyState></Card>:<><div className={`grid gap-4 sm:grid-cols-2 ${kind==="company"?"xl:grid-cols-4":"xl:grid-cols-5"}`}>{cards.map(([title,key,format])=>{const missing=key.includes("rate")&&Number(totals?.missing_rate_count)>0;return <Card key={key} className="flex min-h-28 flex-col justify-between"><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{format==="money"?showMoney(String(totals?.[key]??0)):totals?.[key]??0}</p>{missing&&<p className="text-xs font-semibold text-amber-600">MISSING: {totals?.missing_rate_count}</p>}</Card>})}</div><DataTable>{kind==="company"?<CompanyTable report={report as CompanyBillingReport}/>:<ExecutiveTable report={report as ExecutivePerformanceReport} onView={setSelected}/>}</DataTable></>}
    </>}{selected&&<VisitDetailsModal row={selected} onClose={()=>setSelected(null)}/>} {false&&<DetailsModal row={selected!} onClose={()=>setSelected(null)}/>}</PageContainer>;
}

function CompanyTable({report}:{report:CompanyBillingReport}){return <table className="min-w-[1550px]"><thead><tr>{companyHeaders.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{report.items.map((x,i)=><tr key={`${x.date}-${x.los}-${i}`}><td>{x.date}</td>{[x.los,x.bank,x.visit_type,x.applicant,x.address,x.dist,x.city,x.mobile_number,x.executive,x.status].map((v,j)=><td key={j}>{label(v)}</td>)}<td className="whitespace-nowrap">{showMoney(x.executive_rate,x.executive_rate_status)}</td><td className="whitespace-nowrap">{showMoney(x.company_rate,x.company_rate_status)}</td><td>{x.payment_status}</td></tr>)}</tbody></table>}
function ExecutiveTable({report,onView}:{report:ExecutivePerformanceReport;onView:(row:ExecutiveBankRow)=>void}){return <table className="min-w-[950px]"><thead><tr>{executiveHeaders.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{report.items.map(x=><tr key={`${x.executive}-${x.bank_finance_company}`}><td><span className="line-clamp-2" title={x.executive}>{x.executive}</span></td><td><span className="line-clamp-2" title={x.bank_finance_company}>{x.bank_finance_company}</span></td>{[x.total_cases_visits,x.pending,x.positive,x.negative].map((v,i)=><td className="text-right tabular-nums" key={i}>{v}</td>)}<td className="whitespace-nowrap text-right">{showMoney(x.executive_rate_total,x.rate_status)}</td><td><button type="button" onClick={()=>onView(x)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-1.5 text-sm"><Eye size={15}/>View</button></td></tr>)}</tbody></table>}
function DetailsModal({row,onClose}:{row:ExecutiveBankRow;onClose:()=>void}){return <ModalShell title="Executive Visit Details" subtitle={`${row.executive} · ${row.bank_finance_company}`} onClose={onClose} footer={<button onClick={onClose} className="rounded-xl bg-slate-900 px-4 py-2 text-white">Close</button>}><div className="mb-4 grid gap-3 sm:grid-cols-3"><Info label="Address" value={label(row.address)}/><Info label="Mobile" value={label(row.mobile)}/><Info label="Total visits" value={String(row.total_cases_visits)}/><Info label="Total executive payment" value={showMoney(row.executive_rate_total,row.rate_status)}/></div><DataTable><table className="min-w-[1100px]"><thead><tr>{detailHeaders.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{row.details.map((x,i)=><tr key={i}>{[x.date,x.los,x.applicant,x.visit_type,x.company,x.bank,x.district,x.city,x.status].map((v,j)=><td key={j}>{label(v)}</td>)}<td className="whitespace-nowrap text-right">{showMoney(x.executive_rate,x.executive_rate_status)}</td></tr>)}</tbody></table></DataTable></ModalShell>}
function Info({label:heading,value}:{label:string;value:string}){return <div className="rounded-xl border p-3"><p className="text-xs font-semibold uppercase text-slate-500">{heading}</p><p className="mt-1 font-medium">{value}</p></div>}
function VisitDetailsModal({row,onClose}:{row:ExecutiveBankRow;onClose:()=>void}){return <ModalShell title="Executive Visit Details" subtitle={`${row.executive} · ${row.bank_finance_company}`} onClose={onClose} footer={<button onClick={onClose} className="rounded-xl bg-slate-900 px-4 py-2 text-white">Close</button>}><div className="mb-4 grid gap-3 sm:grid-cols-2"><Info label="Total visits" value={String(row.total_cases_visits)}/><Info label="Total executive payment" value={showMoney(row.executive_rate_total,row.rate_status)}/></div><DataTable><table className="min-w-[1350px]"><thead><tr>{detailHeaders.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{row.details.map((x,i)=><tr key={i}>{[x.date,x.los,x.applicant,x.address,x.mobile,x.visit_type,x.company,x.bank,x.district,x.city,x.status].map((v,j)=><td key={j}>{label(v)}</td>)}<td className="whitespace-nowrap text-right">{showMoney(x.executive_rate,x.executive_rate_status)}</td></tr>)}</tbody></table></DataTable></ModalShell>}
