import { useEffect, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";
import { getBillingDashboard } from "../../services/monthlyBillingService";
import type { BillingDashboard } from "../../types/monthlyBilling";

const currentMonth=()=>new Date().toISOString().slice(0,7);
const money=(value:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(value));

export default function BillingDashboardPage(){
 const [month,setMonth]=useState(currentMonth()); const [data,setData]=useState<BillingDashboard|null>(null);
 const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{let active=true;setLoading(true);setError("");getBillingDashboard(month).then(x=>active&&setData(x)).catch(e=>active&&setError(e instanceof Error?e.message:"Unable to load dashboard")).finally(()=>active&&setLoading(false));return()=>{active=false}},[month]);
 const cards=data?[['Total Bank / Finance Billing',data.total_bank_billing],['Bank / Finance Received',data.bank_received],['Bank / Finance Outstanding',data.bank_outstanding],['Total Executive Payout',data.total_executive_payout],['Executive Paid',data.executive_paid],['Executive Outstanding',data.executive_outstanding],['Expected Gross Margin',data.expected_gross_margin],['Realized Cash Margin',data.realized_cash_margin]]:[];
 return <DashboardLayout><section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-orange-600">Billing</p><h1 className="text-3xl font-bold">Billing Dashboard</h1></div><label className="text-sm">Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="ml-2 rounded-xl border bg-white px-3 py-2 dark:bg-slate-900"/></label></div>
 {loading&&<p className="rounded-xl border p-6">Loading billing dashboard…</p>}{error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{data&&<><div className="flex gap-3 text-sm"><span className="rounded-full bg-orange-100 px-3 py-1 font-semibold text-orange-800">{data.month_status.status}</span><span>Revision {data.month_status.revision_number}</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{money(value)}</p></article>)}</div>
 <Summary title="Bank / Finance Collection Summary" headers={['Bank / Finance Company','City','Billed','Received','Balance','Status']} rows={data.bank_summary.map(x=>[x.bank,x.city||'—',money(x.billed_amount),money(x.received_amount),money(x.balance_amount),x.status])}/>
 <Summary title="Executive Payment Summary" headers={['Executive','Points','Gross','Advance','Net','Paid','Balance','Status']} rows={data.executive_summary.map(x=>[x.executive,String(x.total_points),money(x.gross_payment||'0'),money(x.advance),money(x.net_payment||'0'),money(x.paid),money(x.balance||'0'),x.payment_status])}/></>}</section></DashboardLayout>
}
function Summary({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <div><h2 className="mb-2 text-lg font-bold">{title}</h2><div className="overflow-x-auto rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr>{headers.map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i} className="border-b dark:border-slate-800">{row.map((x,j)=><td key={j} className="p-3">{x}</td>)}</tr>):<tr><td colSpan={headers.length} className="p-8 text-center text-slate-500">No billing data for this month.</td></tr>}</tbody></table></div></div>}
