import { useEffect, useState } from "react";
import * as XLSX from "xlsx";
import { Alert, Card, DataTable, EmptyState, FilterCard, PageContainer, PageHeader } from "../../components/ui";
import { listMasters } from "../../services/masterService";
import { getCompanyBillingReport, getExecutivePerformanceReport } from "../../services/billingReportService";
import type { CompanyBillingReport, ExecutivePerformanceReport } from "../../types/billingReport";

const input="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900";
const companyHeaders=["Date","LOS","Bank","Visit Type","Applicant","Address","Dist","City","Mobile Number","Executive","Status","Executive Rate","Company Rate","Payment Status"];
const bankHeaders=["Executive","Bank / Finance Company","Address","Mobile","Total Cases/Visits","Pending","Positive","Negative","Executive Rate Total"];
const execHeaders=["Executive","Address","Mobile","Total Visits","Pending","Positive","Negative","Total Payment"];
const money=(value:string|null,status:string)=>value===null?status:value;

export default function BillingReportsPage({kind}:{kind:"company"|"executive"}) {
  const [filters,setFilters]=useState({company_id:"",date_from:"",date_to:"",bank:"",district_id:"",city:"",executive:"",visit_type:"",status:"",payment_status:""});
  const [companies,setCompanies]=useState<{id:number;name:string}[]>([]); const [executives,setExecutives]=useState<{full_name:string}[]>([]); const [districts,setDistricts]=useState<{id:number;name:string}[]>([]);
  const [report,setReport]=useState<CompanyBillingReport|ExecutivePerformanceReport|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{void Promise.all([listMasters("companies",{all:true}),listMasters("executives",{all:true}),listMasters("districts",{all:true})]).then(([c,e,d])=>{setCompanies(c.items);setExecutives(e.items);setDistricts(d.items)}).catch(()=>setError("Unable to load report filters."))},[]);
  const params=()=>Object.fromEntries(Object.entries(filters).filter(([key,v])=>v!=="" && (kind==="company" || !["visit_type","payment_status"].includes(key))));
  const preview=async()=>{setBusy(true);setError("");try{setReport(kind==="company"?await getCompanyBillingReport(params()):await getExecutivePerformanceReport(params()))}catch(e){setError((e as {response?:{data?:{detail?:string}}}).response?.data?.detail||"Unable to load report.")}finally{setBusy(false)}};
  const download=()=>{if(!report)return;const wb=XLSX.utils.book_new();if(kind==="company"){const r=report as CompanyBillingReport;XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([companyHeaders,...r.items.map(x=>[x.date,x.los,x.bank,x.visit_type,x.applicant,x.address,x.dist,x.city,x.mobile_number,x.executive,x.status,money(x.executive_rate,x.executive_rate_status),money(x.company_rate,x.company_rate_status),x.payment_status])]),"Company Billing");const company=companies.find(x=>String(x.id)===filters.company_id)?.name.replace(/[^a-z0-9]+/gi,"_")||"company";XLSX.writeFile(wb,`company_billing_${company}_${filters.date_from}_to_${filters.date_to}.xlsx`)}else{const r=report as ExecutivePerformanceReport;XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([bankHeaders,...r.items.map(x=>[x.executive,x.bank_finance_company,x.address,x.mobile,x.total_cases_visits,x.pending,x.positive,x.negative,money(x.executive_rate_total,x.rate_status)])]),"Executive + Bank Summary");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([execHeaders,...r.executive_summary.map(x=>[x.executive,x.address,x.mobile,x.total_visits,x.pending,x.positive,x.negative,money(x.total_payment,x.rate_status)])]),"Executive Summary");XLSX.writeFile(wb,`executive_performance_${filters.date_from}_to_${filters.date_to}.xlsx`)}};
  const set=(key:string,value:string)=>setFilters(x=>({...x,[key]:value}));
  return <PageContainer><PageHeader eyebrow="Billing reports" title={kind==="company"?"Company Billing Export":"Executive Performance Report"} subtitle="Authoritative, permission-scoped visit-level reporting." />
    <FilterCard onSubmit={e=>{e.preventDefault();void preview()}}><div className="grid gap-3 md:grid-cols-4">
      {kind==="company"&&<select required className={input} value={filters.company_id} onChange={e=>set("company_id",e.target.value)}><option value="">Company (required)</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}
      <input required type="date" className={input} value={filters.date_from} onChange={e=>set("date_from",e.target.value)}/><input required type="date" className={input} value={filters.date_to} onChange={e=>set("date_to",e.target.value)}/>
      {kind==="executive"&&<select className={input} value={filters.company_id} onChange={e=>set("company_id",e.target.value)}><option value="">All companies</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}
      <input className={input} placeholder="Bank / Finance Company" value={filters.bank} onChange={e=>set("bank",e.target.value)}/><select className={input} value={filters.district_id} onChange={e=>set("district_id",e.target.value)}><option value="">All districts</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={input} placeholder="City" value={filters.city} onChange={e=>set("city",e.target.value)}/><select className={input} value={filters.executive} onChange={e=>set("executive",e.target.value)}><option value="">All executives</option>{executives.map(x=><option key={x.full_name}>{x.full_name}</option>)}</select>
      {kind==="company"&&<><select className={input} value={filters.visit_type} onChange={e=>set("visit_type",e.target.value)}><option value="">All visit types</option>{["Residence","Office","Permanent","Business","Other"].map(x=><option key={x}>{x}</option>)}</select><select className={input} value={filters.payment_status} onChange={e=>set("payment_status",e.target.value)}><option value="">All payment states</option>{["Pending","Partially Paid","Paid","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></>}
      <select className={input} value={filters.status} onChange={e=>set("status",e.target.value)}><option value="">All statuses</option>{["Pending","Positive","Negative"].map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-4 flex gap-3"><button className="rounded-xl bg-orange-600 px-5 py-2 text-white" disabled={busy}>{busy?"Loading…":"Preview"}</button><button type="button" onClick={download} disabled={!report} className="rounded-xl border px-5 py-2 disabled:opacity-50">Download Excel</button></div></FilterCard>
    {error&&<Alert>{error}</Alert>}{report&&<><Alert tone={report.metadata.contains_draft?"warning":"success"}>{report.metadata.state} report. {report.metadata.limitations.join(" ")}</Alert><Card><p className="font-semibold">{report.totals.visits??report.totals.rows} visit rows</p></Card><DataTable>{report.items.length===0?<EmptyState>No matching visits.</EmptyState>:kind==="company"?<CompanyTable report={report as CompanyBillingReport}/>:<ExecutiveTable report={report as ExecutivePerformanceReport}/>}</DataTable></>}
  </PageContainer>;
}
function CompanyTable({report}:{report:CompanyBillingReport}){return <table className="min-w-[1550px] w-full text-sm"><thead><tr>{companyHeaders.map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{report.items.map((x,i)=><tr key={i} className="border-t"><td className="p-3">{x.date}</td>{[x.los,x.bank,x.visit_type,x.applicant,x.address,x.dist,x.city,x.mobile_number,x.executive,x.status,money(x.executive_rate,x.executive_rate_status),money(x.company_rate,x.company_rate_status),x.payment_status].map((v,j)=><td key={j} className="p-3">{v||"—"}</td>)}</tr>)}</tbody></table>}
function ExecutiveTable({report}:{report:ExecutivePerformanceReport}){return <table className="min-w-[1050px] w-full text-sm"><thead><tr>{bankHeaders.map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{report.items.map((x,i)=><tr key={i} className="border-t">{[x.executive,x.bank_finance_company,x.address,x.mobile,x.total_cases_visits,x.pending,x.positive,x.negative,money(x.executive_rate_total,x.rate_status)].map((v,j)=><td key={j} className="p-3">{v??"—"}</td>)}</tr>)}</tbody></table>}
