import { useEffect, useRef, useState } from "react";
import { Download, Pencil, Plus, Search, Upload } from "lucide-react";
import * as XLSX from "xlsx";
import { useLocation } from "react-router-dom";
import DashboardLayout from "../../layouts/DashboardLayout";
import { listMasters } from "../../services/masterService";
import { importPayoutRates, listPayoutRates, savePayoutRate } from "../../services/payoutRateService";
import type { Bank, Company, CompanyBank, District, Executive } from "../../types/master";
import type { ImportRateRow, PayoutRate, RateKind, RatePayload } from "../../types/payoutRate";

const control="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm";
const display=(value:string|null|undefined)=>value||"All";
export default function RateMastersPage() {
  const location=useLocation(); const kind:RateKind=location.pathname.includes("executive")?"executive":"bank";
  const [rates,setRates]=useState<PayoutRate[]>([]); const [banks,setBanks]=useState<Bank[]>([]); const [executives,setExecutives]=useState<Executive[]>([]);
  const [companies,setCompanies]=useState<Company[]>([]); const [companyBanks,setCompanyBanks]=useState<CompanyBank[]>([]); const [districts,setDistricts]=useState<District[]>([]);
  const [search,setSearch]=useState(""); const [editing,setEditing]=useState<PayoutRate|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState("");
  const [form,setForm]=useState<RatePayload>({payout_rate:0,effective_from:new Date().toISOString().slice(0,10),is_active:true});
  const fileRef=useRef<HTMLInputElement>(null);
  const load=async()=>{try{const all=await listPayoutRates(kind,search);setRates(all.filter(rate=>kind==="executive"?"executive_id" in rate&&!rate.bank_id&&!rate.city&&!rate.loan_type&&!rate.product_type:!("executive_id" in rate)&&!!rate.company_id&&!!rate.district_id));setError("");}catch(e){setError((e as Error).message)}};
  useEffect(()=>{void load();},[kind]); useEffect(()=>{void Promise.all([listMasters("banks",{all:true}),listMasters("executives",{all:true}),listMasters("companies",{all:true,activeOnly:true}),listMasters("company-banks",{all:true,activeOnly:true}),listMasters("districts",{all:true,activeOnly:true})]).then(([b,e,c,cb,d])=>{setBanks(b.items);setExecutives(e.items);setCompanies(c.items);setCompanyBanks(cb.items);setDistricts(d.items)})},[]);
  const begin=(rate?:PayoutRate)=>{setEditing(rate||null);setForm(rate?{bank_id:rate.bank_id,company_id:"company_id" in rate?rate.company_id:undefined,district_id:"district_id" in rate?rate.district_id:undefined,executive_id:"executive_id" in rate?rate.executive_id:undefined,city:rate.city,payout_rate:Number(rate.payout_rate),effective_from:rate.effective_from,effective_to:rate.effective_to,is_active:rate.is_active,remarks:rate.remarks}:{bank_id:kind==="bank"?undefined:null,payout_rate:0,effective_from:new Date().toISOString().slice(0,10),is_active:true});setOpen(true)};
  const payload=(source:RatePayload):RatePayload=>kind==="executive"?{executive_id:source.executive_id,bank_id:null,city:null,loan_type:null,product_type:null,payout_rate:source.payout_rate,effective_from:source.effective_from,effective_to:source.effective_to||null,is_active:source.is_active,remarks:source.remarks||null}:{company_id:source.company_id,bank_id:source.bank_id,district_id:source.district_id,city:source.city?.trim()||null,loan_type:null,product_type:null,state:"Rajasthan",payout_rate:source.payout_rate,effective_from:source.effective_from,effective_to:source.effective_to||null,is_active:source.is_active,remarks:source.remarks||null};
  const save=async(e:React.FormEvent)=>{e.preventDefault();try{await savePayoutRate(kind,payload(form),editing?.id);setOpen(false);await load()}catch(err){setError((err as Error).message)}};
  const toggle=async(rate:PayoutRate)=>{try{await savePayoutRate(kind,payload({bank_id:rate.bank_id,company_id:"company_id" in rate?rate.company_id:undefined,district_id:"district_id" in rate?rate.district_id:undefined,executive_id:"executive_id" in rate?rate.executive_id:undefined,city:rate.city,payout_rate:Number(rate.payout_rate),effective_from:rate.effective_from,effective_to:rate.effective_to,is_active:!rate.is_active,remarks:rate.remarks}),rate.id);await load()}catch(e){setError((e as Error).message)}};
  const mappedBanks=banks.filter(bank=>companyBanks.some(mapping=>mapping.company_id===form.company_id&&mapping.bank_id===bank.id&&mapping.is_active));
  const selectedDistrict=districts.find(district=>district.id===form.district_id);
  const isJaipur=selectedDistrict?.name.trim().toLowerCase()==="jaipur";
  const exportTemplate=()=>{const columns=["Company","Bank","District","City","Payout Rate","Effective From","Effective To","Active","Remarks"];const sheet=XLSX.utils.json_to_sheet([Object.fromEntries(columns.map(x=>[x,""]))],{header:columns});const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"Bank Rates");XLSX.writeFile(book,"bank-rate-template.xlsx")};
  const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const book=XLSX.read(await file.arrayBuffer(),{cellDates:true});const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[book.SheetNames[0]],{defval:""});const dateValue=(v:unknown)=>v instanceof Date?v.toISOString().slice(0,10):String(v||"").slice(0,10);const rows:ImportRateRow[]=raw.map((r,i)=>({row_number:i+2,company:String(r.Company||""),bank:String(r.Bank||""),district:String(r.District||""),city:String(r.City||""),payout_rate:Number(r["Payout Rate"]),effective_from:dateValue(r["Effective From"]),effective_to:dateValue(r["Effective To"])||undefined,active:!["false","no","0","inactive"].includes(String(r.Active).toLowerCase()),remarks:String(r.Remarks||"")}));const preview=await importPayoutRates("bank",rows,false);if(preview.invalid_count){setError(`Import preview rejected ${preview.invalid_count} row(s): ${preview.rows.filter(x=>!x.valid).slice(0,5).map(x=>`Row ${x.row_number}: ${x.errors.join("; ")}`).join(" | ")}`)}else if(window.confirm(`${preview.valid_count} valid rows. Import now?`)){await importPayoutRates("bank",rows,true);await load()}}catch(err){setError((err as Error).message)}finally{e.target.value=""}};
  if(kind==="bank") return <DashboardLayout><section className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-orange-600">Billing</p><h1 className="text-3xl font-bold">Bank Rate Master</h1><p className="mt-1 text-sm text-slate-500">City-specific rates are available only for Jaipur district. Other districts use All Cities.</p></div><div className="flex gap-2"><button onClick={exportTemplate} className="flex items-center gap-2 rounded-xl border px-3 py-2"><Download size={16}/>Template</button><button onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 rounded-xl border px-3 py-2"><Upload size={16}/>Import</button><input ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>void importFile(e)}/><button onClick={()=>begin()} className="flex items-center gap-2 rounded-xl bg-orange-600 px-4 py-2.5 text-white"><Plus size={17}/>Add Rate</button></div></div>
    <form onSubmit={e=>{e.preventDefault();void load()}} className="flex gap-2"><input className={control} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search rates"/><button className="rounded-xl bg-slate-900 px-4 text-white"><Search size={17}/></button></form>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="overflow-x-auto rounded-2xl border bg-white dark:border-slate-700 dark:bg-slate-900"><table className="w-full min-w-[1150px] text-sm"><thead className="bg-slate-900 text-white"><tr>{["COMPANY","BANK","DISTRICT","CITY / LOCATION","RATE","EFFECTIVE FROM","EFFECTIVE TO","ACTIVE","ACTION"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rates.map(rate=>"company_name" in rate&&<tr key={rate.id} className="border-b dark:border-slate-700"><td className="p-3 font-medium">{rate.company_name}</td><td className="p-3">{rate.bank_name}</td><td className="p-3">{rate.district_name}</td><td className="p-3">{rate.city||"All Cities"}</td><td className="p-3">₹{Number(rate.payout_rate).toFixed(2)}</td><td className="p-3">{rate.effective_from}</td><td className="p-3">{rate.effective_to||"Open"}</td><td className="p-3"><button onClick={()=>void toggle(rate)} className={`rounded-full px-3 py-1 ${rate.is_active?"bg-green-100 text-green-700":"bg-slate-100 dark:bg-slate-700"}`}>{rate.is_active?"Active":"Inactive"}</button></td><td className="p-3"><button onClick={()=>begin(rate)}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={save} className="w-full max-w-xl space-y-4 rounded-2xl bg-white p-6 dark:bg-slate-900"><h2 className="text-xl font-bold">{editing?"Edit":"Add"} Bank Rate</h2><label className="block">Company<select required className={`${control} mt-1 w-full`} value={form.company_id||""} onChange={e=>setForm({...form,company_id:Number(e.target.value),bank_id:undefined})}><option value="">Select company</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block">Bank<select required disabled={!form.company_id} className={`${control} mt-1 w-full`} value={form.bank_id||""} onChange={e=>setForm({...form,bank_id:Number(e.target.value)})}><option value="">Select mapped bank</option>{mappedBanks.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block">District<select required className={`${control} mt-1 w-full`} value={form.district_id||""} onChange={e=>{const districtId=Number(e.target.value);const jaipur=districts.find(x=>x.id===districtId)?.name.trim().toLowerCase()==="jaipur";setForm({...form,district_id:districtId,city:jaipur?form.city:null})}}><option value="">Select district</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block">City / Location<input disabled={!isJaipur} placeholder={isJaipur?"Blank means All Cities":"All Cities"} className={`${control} mt-1 w-full disabled:opacity-60`} value={form.city||""} onChange={e=>setForm({...form,city:e.target.value||null})}/><span className="mt-1 block text-xs text-slate-500">City-specific rates are available only for Jaipur district.</span></label><label className="block">Payout Rate<input required min="0" step="0.01" type="number" className={`${control} mt-1 w-full`} value={form.payout_rate} onChange={e=>setForm({...form,payout_rate:Number(e.target.value)})}/></label><div className="grid grid-cols-2 gap-3"><label>Effective From<input required type="date" className={`${control} mt-1 w-full`} value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Effective To<input type="date" className={`${control} mt-1 w-full`} value={form.effective_to||""} onChange={e=>setForm({...form,effective_to:e.target.value||null})}/></label></div><label className="flex gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Active</label><label className="block">Remarks<textarea className={`${control} mt-1 w-full`} value={form.remarks||""} onChange={e=>setForm({...form,remarks:e.target.value||null})}/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2">Cancel</button><button className="rounded-xl bg-orange-600 px-4 py-2 text-white">Save</button></div></form></div>}
  </section></DashboardLayout>;
  return <DashboardLayout><section className="space-y-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-orange-600">Billing</p><h1 className="text-3xl font-bold">{kind==="executive"?"Executive":"Bank"} Rate Master</h1><p className="mt-1 text-sm text-slate-500">{kind==="executive"?"One fixed effective rate per executive.":"Effective rates match exact Bank + City."}</p></div><button onClick={()=>begin()} className="flex items-center gap-2 rounded-xl bg-orange-600 px-4 py-2.5 text-white"><Plus size={17}/>Add Rate</button></div><form onSubmit={e=>{e.preventDefault();void load()}} className="flex gap-2"><input className={control} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search rates"/><button className="rounded-xl bg-slate-900 px-4 text-white"><Search size={17}/></button></form>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="overflow-x-auto rounded-2xl border bg-white dark:border-slate-700 dark:bg-slate-900"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-900 text-white"><tr>{(kind==="executive"?["EXECUTIVE","BANK","CITY","LOAN TYPE","PRODUCT TYPE","RATE","EFFECTIVE","ACTIVE","ACTION"]:["BANK","CITY","RATE","EFFECTIVE FROM","EFFECTIVE TO","ACTIVE","ACTION"]).map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rates.map(rate=><tr key={rate.id} className="border-b dark:border-slate-700">{kind==="executive"&&"executive_name" in rate?<><td className="p-3 font-medium">{rate.executive_name}</td><td className="p-3">{display(rate.bank_name)}</td><td className="p-3">{display(rate.city)}</td><td className="p-3">{display(rate.loan_type)}</td><td className="p-3">{display(rate.product_type)}</td></>:<><td className="p-3 font-medium">{rate.bank_name}</td><td className="p-3">{rate.city}</td></>}<td className="p-3">₹{Number(rate.payout_rate).toFixed(2)}</td>{kind==="executive"?<td className="p-3">{rate.effective_from} – {rate.effective_to||"Open"}</td>:<><td className="p-3">{rate.effective_from}</td><td className="p-3">{rate.effective_to||"Open"}</td></>}<td className="p-3"><button onClick={()=>void toggle(rate)} className={`rounded-full px-3 py-1 ${rate.is_active?"bg-green-100 text-green-700":"bg-slate-100 dark:bg-slate-700 dark:text-slate-200"}`}>{rate.is_active?"Active":"Inactive"}</button></td><td className="p-3"><button onClick={()=>begin(rate)}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={save} className="w-full max-w-xl space-y-4 rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">{editing?"Edit":"Add"} Rate</h2>{kind==="executive"?<label className="block">Executive<input required list="executives" className={`${control} mt-1`} defaultValue={editing&&"executive_name" in editing?editing.executive_name:""} onChange={e=>setForm({...form,executive_id:executives.find(x=>x.full_name.trim().toLowerCase()===e.target.value.trim().toLowerCase())?.id})}/><datalist id="executives">{executives.map(x=><option key={x.id} value={x.full_name}/>)}</datalist></label>:<><label className="block">Bank<select required className={`${control} mt-1`} value={form.bank_id||""} onChange={e=>setForm({...form,bank_id:Number(e.target.value)})}><option value="">Select bank</option>{banks.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block">City<input required className={`${control} mt-1`} value={form.city||""} onChange={e=>setForm({...form,city:e.target.value})}/></label></>}<label className="block">Payout Rate<input required min="0" step="0.01" type="number" className={`${control} mt-1`} value={form.payout_rate} onChange={e=>setForm({...form,payout_rate:Number(e.target.value)})}/></label><div className="grid grid-cols-2 gap-3"><label>Effective From<input required type="date" className={`${control} mt-1`} value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Effective To<input type="date" className={`${control} mt-1`} value={form.effective_to||""} onChange={e=>setForm({...form,effective_to:e.target.value||null})}/></label></div><label className="flex gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Active</label><label className="block">Remarks<textarea className={`${control} mt-1`} value={form.remarks||""} onChange={e=>setForm({...form,remarks:e.target.value||null})}/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2">Cancel</button><button className="rounded-xl bg-orange-600 px-4 py-2 text-white">Save</button></div></form></div>}</section></DashboardLayout>;
}
