import { useEffect, useState } from "react";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useLocation } from "react-router-dom";
import DashboardLayout from "../../layouts/DashboardLayout";
import MultiSelectCheckboxDropdown from "../../components/MultiSelectCheckboxDropdown";
import { listMasters } from "../../services/masterService";
import { bulkCreateBankRates, deleteBankRate, listPayoutRates, savePayoutRate } from "../../services/payoutRateService";
import type { Bank, Company, District, Executive } from "../../types/master";
import type { DistrictScope, PayoutRate, RateKind, RatePayload } from "../../types/payoutRate";

const control="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm";
const today=()=>new Date().toISOString().slice(0,10);

export default function RateMastersPage() {
  const kind:RateKind=useLocation().pathname.includes("executive")?"executive":"bank";
  const [rates,setRates]=useState<PayoutRate[]>([]);
  const [banks,setBanks]=useState<Bank[]>([]); const [companies,setCompanies]=useState<Company[]>([]);
  const [districts,setDistricts]=useState<District[]>([]); const [executives,setExecutives]=useState<Executive[]>([]);
  const [editing,setEditing]=useState<PayoutRate|null>(null); const [open,setOpen]=useState(false);
  const [error,setError]=useState(""); const [message,setMessage]=useState(""); const search="";
  const [bankScope,setBankScope]=useState<"all"|"selected">("all");
  const [districtScope,setDistrictScope]=useState<DistrictScope>("RAJASTHAN_EXCEPT_JAIPUR");
  const [selectedBankIds,setSelectedBankIds]=useState<number[]>([]); const [selectedDistrictIds,setSelectedDistrictIds]=useState<number[]>([]);
  const [filters,setFilters]=useState({company_id:"",bank_id:"",district_id:"",scope:"",active:""});
  const [form,setForm]=useState<RatePayload>({payout_rate:0,effective_from:today(),is_active:true});

  const load=async()=>{try{const query=kind==="bank"?Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=="").map(([k,v])=>[k,k==="active"?v==="true":Number.isNaN(Number(v))?v:Number(v)])):{};const rows=await listPayoutRates(kind,search,query);setRates(rows.filter(r=>kind==="bank"?!('executive_id' in r)&&!!r.company_id:'executive_id' in r&&!r.bank_id&&!r.city&&!r.loan_type&&!r.product_type));setError("")}catch(e){setError((e as Error).message)}};
  useEffect(()=>{void load()},[kind]);
  useEffect(()=>{void Promise.all([listMasters("banks",{all:true}),listMasters("companies",{all:true,activeOnly:true}),listMasters("districts",{all:true,activeOnly:true}),listMasters("executives",{all:true})]).then(([b,c,d,e])=>{setBanks(b.items);setCompanies(c.items);setDistricts(d.items);setExecutives(e.items)})},[]);

  const begin=(rate?:PayoutRate)=>{setEditing(rate||null);setError("");setMessage("");setSelectedBankIds([]);setSelectedDistrictIds([]);setBankScope(rate&&rate.bank_id!==null?"selected":"all");setDistrictScope(rate&&"district_scope" in rate&&rate.district_scope?rate.district_scope:"RAJASTHAN_EXCEPT_JAIPUR");setForm(rate?{bank_id:rate.bank_id,company_id:"company_id" in rate?rate.company_id:undefined,district_id:"district_id" in rate?rate.district_id:undefined,district_scope:"district_scope" in rate?rate.district_scope:undefined,executive_id:"executive_id" in rate?rate.executive_id:undefined,city:rate.city,payout_rate:Number(rate.payout_rate),effective_from:rate.effective_from,effective_to:rate.effective_to,is_active:rate.is_active,remarks:rate.remarks}:{bank_id:null,district_scope:"RAJASTHAN_EXCEPT_JAIPUR",payout_rate:0,effective_from:today(),is_active:true});setOpen(true)};
  const common=(source:RatePayload):RatePayload=>({company_id:source.company_id,bank_id:source.bank_id,district_id:source.district_id,district_scope:source.district_scope,executive_id:source.executive_id,city:source.city?.trim()||null,loan_type:null,product_type:null,state:"Rajasthan",payout_rate:source.payout_rate,effective_from:source.effective_from,effective_to:source.effective_to||null,is_active:source.is_active,remarks:source.remarks||null});
  const save=async(e:React.FormEvent)=>{e.preventDefault();setError("");try{if(kind==="executive"){await savePayoutRate(kind,{...common(form),bank_id:null,city:null},editing?.id)}else if(editing){await savePayoutRate(kind,common({...form,bank_id:bankScope==="all"?null:form.bank_id,district_scope:districtScope}),editing.id)}else{if(bankScope==="selected"&&!selectedBankIds.length)throw new Error("Select at least one bank");if(districtScope==="SELECTED_DISTRICTS"&&!selectedDistrictIds.length)throw new Error("Select at least one district");if(districtScope==="SELECTED_DISTRICTS"&&form.city&&selectedDistrictIds.length!==1)throw new Error("City can be entered only when Jaipur is the only selected district");const data=common({...form,district_scope:districtScope});const result=await bulkCreateBankRates({...data,company_id:Number(data.company_id),bank_ids:bankScope==="all"?null:selectedBankIds,district_ids:districtScope==="SELECTED_DISTRICTS"?selectedDistrictIds:null,district_scope:districtScope});setMessage(`${result.created_count} bank rate rule(s) added`)}setOpen(false);await load()}catch(err){setError((err as Error).message)}};
  const toggle=async(rate:PayoutRate)=>{try{await savePayoutRate(kind,common({bank_id:rate.bank_id,company_id:"company_id" in rate?rate.company_id:undefined,district_id:"district_id" in rate?rate.district_id:undefined,district_scope:"district_scope" in rate?rate.district_scope:undefined,executive_id:"executive_id" in rate?rate.executive_id:undefined,city:rate.city,payout_rate:Number(rate.payout_rate),effective_from:rate.effective_from,effective_to:rate.effective_to,is_active:!rate.is_active,remarks:rate.remarks}),rate.id);await load()}catch(e){setError((e as Error).message)}};
  const remove=async(rate:PayoutRate)=>{if(!window.confirm("Delete this bank rate? This action cannot be undone."))return;try{await deleteBankRate(rate.id);await load()}catch(e){setError((e as Error).message)}};
  const jaipur=districts.find(d=>d.name.trim().toLowerCase()==="jaipur");
  const cityEnabled=districtScope==="JAIPUR_ONLY"||(districtScope==="SELECTED_DISTRICTS"&&selectedDistrictIds.length===1&&selectedDistrictIds[0]===jaipur?.id)||(!!editing&&districtScope==="SELECTED_DISTRICTS"&&form.district_id===jaipur?.id);

  if(kind==="executive") return <DashboardLayout><section className="space-y-5"><div className="flex justify-between"><h1 className="text-3xl font-bold">Executive Rate Master</h1><button onClick={()=>begin()} className="rounded-xl bg-orange-600 px-4 py-2 text-white"><Plus className="inline" size={17}/> Add Rate</button></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<table className="w-full text-sm"><thead><tr>{["Executive","Rate","Effective","Active","Action"].map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rates.map(r=>"executive_name" in r&&<tr className="border-t" key={r.id}><td className="p-3">{r.executive_name}</td><td className="p-3">₹{r.payout_rate}</td><td className="p-3">{r.effective_from} – {r.effective_to||"Open"}</td><td className="p-3"><button onClick={()=>void toggle(r)}>{r.is_active?"Active":"Inactive"}</button></td><td className="p-3"><button onClick={()=>begin(r)}><Pencil size={16}/></button></td></tr>)}</tbody></table>{open&&<RateDialog title={`${editing?"Edit":"Add"} Executive Rate`} save={save} close={()=>setOpen(false)}><label>Executive<select required className={control} value={form.executive_id||""} onChange={e=>setForm({...form,executive_id:Number(e.target.value)})}><option value="">Select executive</option>{executives.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><RateFields form={form} setForm={setForm}/></RateDialog>}</section></DashboardLayout>;

  return <DashboardLayout><section className="space-y-5">
    <div className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase text-orange-600">Billing</p><h1 className="text-3xl font-bold">Bank Rate Master</h1></div><button onClick={()=>begin()} className="rounded-xl bg-orange-600 px-4 py-2 text-white"><Plus className="inline" size={17}/> Add Rate</button></div>
    <form onSubmit={e=>{e.preventDefault();void load()}} className="grid gap-2 md:grid-cols-6"><Filter value={filters.company_id} change={v=>setFilters({...filters,company_id:v})} label="All Companies" items={companies}/><Filter value={filters.bank_id} change={v=>setFilters({...filters,bank_id:v})} label="All Banks" items={banks}/><Filter value={filters.district_id} change={v=>setFilters({...filters,district_id:v})} label="All Districts" items={districts}/><select className={control} value={filters.scope} onChange={e=>setFilters({...filters,scope:e.target.value})}><option value="">All scopes</option><option value="rajasthan_except_jaipur">Rajasthan Except Jaipur</option><option value="jaipur">Jaipur</option><option value="specific">Specific District</option></select><select className={control} value={filters.active} onChange={e=>setFilters({...filters,active:e.target.value})}><option value="">Any Status</option><option value="true">Active</option><option value="false">Inactive</option></select><button className="rounded-xl bg-slate-900 text-white"><Search className="mx-auto" size={17}/></button></form>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-green-50 p-3 text-green-700">{message}</p>}
    <div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-900 text-white"><tr>{["Company","Bank Scope","District Scope","City","Rate","Effective","Active","Action"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rates.map(r=>"company_name" in r&&<tr key={r.id} className="border-b"><td className="p-3">{r.company_name}</td><td className="p-3">{r.bank_name||"All Banks"}</td><td className="p-3">{r.district_scope==="RAJASTHAN_EXCEPT_JAIPUR"?"All Rajasthan Except Jaipur":r.district_scope==="JAIPUR_ONLY"?"Jaipur":r.district_name}</td><td className="p-3">{r.city||"All Cities"}</td><td className="p-3">₹{Number(r.payout_rate).toFixed(2)}</td><td className="p-3">{r.effective_from} – {r.effective_to||"Open"}</td><td className="p-3"><button onClick={()=>void toggle(r)}>{r.is_active?"Active":"Inactive"}</button></td><td className="p-3"><div className="flex gap-3"><button aria-label="Edit bank rate" onClick={()=>begin(r)}><Pencil size={16}/></button><button aria-label="Delete bank rate" className="text-red-600" onClick={()=>void remove(r)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>
    {open&&<RateDialog title={`${editing?"Edit":"Add"} Bank Rate`} save={save} close={()=>setOpen(false)}>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<label>Company<select required className={control} value={form.company_id||""} onChange={e=>setForm({...form,company_id:Number(e.target.value)})}><option value="">Select company</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Bank Scope<select className={control} value={bankScope} onChange={e=>setBankScope(e.target.value as "all"|"selected")}><option value="all">All Banks</option><option value="selected">Selected Banks</option></select></label>{bankScope==="selected"&&(editing?<Filter value={String(form.bank_id||"")} change={v=>setForm({...form,bank_id:Number(v)})} label="Select bank" items={banks}/>:<MultiSelectCheckboxDropdown items={banks.map(x=>({id:x.id,label:x.name}))} selectedIds={selectedBankIds} onChange={setSelectedBankIds}/>) }<label>District Scope<select className={control} value={districtScope} onChange={e=>{const scope=e.target.value as DistrictScope;setDistrictScope(scope);setSelectedDistrictIds([]);setForm({...form,district_scope:scope,district_id:null,city:null})}}><option value="RAJASTHAN_EXCEPT_JAIPUR">All Rajasthan Except Jaipur</option><option value="JAIPUR_ONLY">Jaipur Only</option><option value="SELECTED_DISTRICTS">Selected Districts</option></select></label>{districtScope==="RAJASTHAN_EXCEPT_JAIPUR"&&<p className="text-xs text-slate-500">Applies to every Rajasthan district except Jaipur.</p>}{districtScope==="SELECTED_DISTRICTS"&&(editing?<Filter value={String(form.district_id||"")} change={v=>setForm({...form,district_id:Number(v),city:null})} label="Select district" items={districts}/>:<MultiSelectCheckboxDropdown items={districts.map(x=>({id:x.id,label:x.name}))} selectedIds={selectedDistrictIds} onChange={ids=>{setSelectedDistrictIds(ids);if(ids.length!==1||ids[0]!==jaipur?.id)setForm({...form,city:null})}}/>)}<label>City / Location<input disabled={!cityEnabled} className={`${control} disabled:opacity-60`} placeholder={cityEnabled?"Blank means All Cities":"Available only for Jaipur"} value={form.city||""} onChange={e=>setForm({...form,city:e.target.value||null})}/></label><RateFields form={form} setForm={setForm}/></RateDialog>}
  </section></DashboardLayout>;
}

function Filter({value,change,label,items}:{value:string;change:(v:string)=>void;label:string;items:Array<{id:number;name:string}>}) { return <select className={control} value={value} onChange={e=>change(e.target.value)}><option value="">{label}</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select> }
function RateFields({form,setForm}:{form:RatePayload;setForm:(v:RatePayload)=>void}) { return <><label>Rate<input required min="0.01" step="0.01" type="number" className={control} value={form.payout_rate} onChange={e=>setForm({...form,payout_rate:Number(e.target.value)})}/></label><div className="grid grid-cols-2 gap-3"><label>Effective From<input required type="date" className={control} value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Effective To<input type="date" className={control} value={form.effective_to||""} onChange={e=>setForm({...form,effective_to:e.target.value||null})}/></label></div><label><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label><label>Remarks<textarea className={control} value={form.remarks||""} onChange={e=>setForm({...form,remarks:e.target.value||null})}/></label></> }
function RateDialog({title,save,close,children}:{title:string;save:(e:React.FormEvent)=>void;close:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={save} className="max-h-[95vh] w-full max-w-xl space-y-4 overflow-y-auto rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">{title}</h2>{children}<div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border px-4 py-2">Cancel</button><button className="rounded-xl bg-orange-600 px-4 py-2 text-white">Save</button></div></form></div> }
