import { useEffect, useMemo, useRef, useState } from "react";
import { Download, Pencil, Plus, Search, Upload } from "lucide-react";
import * as XLSX from "xlsx";
import DashboardLayout from "../../layouts/DashboardLayout";
import { listMasters } from "../../services/masterService";
import { importPayoutRates, listPayoutRates, savePayoutRate } from "../../services/payoutRateService";
import type { Bank, Executive, LoanType, ProductType } from "../../types/master";
import type { ImportRateRow, PayoutRate, RateKind, RatePayload } from "../../types/payoutRate";

const fields = ["Bank", "State", "City", "Location", "Loan Type", "Product Type", "Payout Rate", "Effective From", "Effective To", "Active", "Remarks"];
const executiveFields = ["Executive", "Bank", "City", "Location", "Loan Type", "Product Type", "Payout Rate", "Effective From", "Effective To", "Active", "Remarks"];
const input = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900";
const blank = (): RatePayload => ({ bank_id: null, payout_rate: 0, effective_from: new Date().toISOString().slice(0, 10), effective_to: null, is_active: true });
const display = (value: string | null | undefined) => value || "All";
const isoDate = (value: unknown) => value instanceof Date ? value.toISOString().slice(0, 10) : String(value || "").slice(0, 10);

export default function RateMastersPage() {
  const [kind, setKind] = useState<RateKind>("bank"); const [rates, setRates] = useState<PayoutRate[]>([]);
  const [banks, setBanks] = useState<Bank[]>([]); const [executives, setExecutives] = useState<Executive[]>([]);
  const [loans, setLoans] = useState<LoanType[]>([]); const [products, setProducts] = useState<ProductType[]>([]);
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<PayoutRate | null>(null);
  const [form, setForm] = useState<RatePayload>(blank()); const [open, setOpen] = useState(false);
  const [message, setMessage] = useState(""); const [importRows, setImportRows] = useState<ImportRateRow[]>([]);
  const [importResult, setImportResult] = useState<Awaited<ReturnType<typeof importPayoutRates>> | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const load = async () => { try { setRates(await listPayoutRates(kind, search)); } catch (e) { setMessage((e as Error).message); } };
  useEffect(() => { void load(); }, [kind]);
  useEffect(() => { void Promise.all([listMasters("banks", { all: true }), listMasters("executives", { all: true }), listMasters("loan-types", { all: true }), listMasters("product-types", { all: true })]).then(([b,e,l,p]) => { setBanks(b.items); setExecutives(e.items); setLoans(l.items); setProducts(p.items); }); }, []);
  const executiveName = useMemo(() => editing && "executive_name" in editing ? editing.executive_name : "", [editing]);
  const startEdit = (rate?: PayoutRate) => { setEditing(rate || null); setForm(rate ? { bank_id: rate.bank_id, executive_id: "executive_id" in rate ? rate.executive_id : undefined, state: "state" in rate ? rate.state : undefined, city: rate.city, loan_type: rate.loan_type, product_type: rate.product_type, payout_rate: Number(rate.payout_rate), effective_from: rate.effective_from, effective_to: rate.effective_to, is_active: rate.is_active, remarks: rate.remarks } : blank()); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { await savePayoutRate(kind, form, editing?.id); setOpen(false); setMessage("Rate saved."); await load(); } catch (e) { setMessage((e as Error).message); } };
  const toggle = async (rate: PayoutRate) => { const payload: RatePayload = { bank_id: rate.bank_id, executive_id: "executive_id" in rate ? rate.executive_id : undefined, state: "state" in rate ? rate.state : undefined, city: rate.city, loan_type: rate.loan_type, product_type: rate.product_type, payout_rate: Number(rate.payout_rate), effective_from: rate.effective_from, effective_to: rate.effective_to, is_active: !rate.is_active, remarks: rate.remarks }; try { await savePayoutRate(kind, payload, rate.id); await load(); } catch(e) { setMessage((e as Error).message); } };
  const template = () => { const columns = kind === "bank" ? fields : executiveFields; const sheet = XLSX.utils.json_to_sheet([Object.fromEntries(columns.map(c => [c, ""]))], { header: columns }); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, kind === "bank" ? "Bank Rates" : "Executive Rates"); XLSX.writeFile(book, `${kind}-payout-rate-template.xlsx`); };
  const parse = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const book = XLSX.read(await file.arrayBuffer(), { cellDates: true }); const raw = XLSX.utils.sheet_to_json<Record<string, unknown>>(book.Sheets[book.SheetNames[0]], { defval: "" }); const rows = raw.map((r, i) => ({ row_number: i + 2, bank: String(r.Bank || ""), executive: String(r.Executive || ""), state: String(r.State || ""), city: String(r.City || ""), location: String(r.Location || ""), loan_type: String(r["Loan Type"] || ""), product_type: String(r["Product Type"] || ""), payout_rate: Number(r["Payout Rate"]), effective_from: isoDate(r["Effective From"]), effective_to: isoDate(r["Effective To"]) || undefined, active: !["no","false","0","inactive"].includes(String(r.Active).toLowerCase()), remarks: String(r.Remarks || "") })); setImportRows(rows); try { setImportResult(await importPayoutRates(kind, rows, false)); } catch(e) { setMessage((e as Error).message); } event.target.value = ""; };
  const confirmImport = async () => { try { const result = await importPayoutRates(kind, importRows, true); setImportResult(result); setMessage(`${result.imported_count} rates imported.`); await load(); } catch(e) { setMessage((e as Error).message); } };
  return <DashboardLayout><section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-orange-600">Billing</p><h1 className="mt-1 text-3xl font-bold dark:text-white">Rate Masters</h1></div><div className="flex flex-wrap gap-2"><button onClick={template} className="flex items-center gap-2 rounded-xl border px-3 py-2"><Download size={16}/>Export {kind === "bank" ? "Bank" : "Executive"} Template</button><button onClick={() => fileRef.current?.click()} className="flex items-center gap-2 rounded-xl border px-3 py-2"><Upload size={16}/>Import Rates</button><input ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={parse}/><button onClick={() => startEdit()} className="flex items-center gap-2 rounded-xl bg-orange-600 px-4 py-2 text-white"><Plus size={16}/>Add Rate</button></div></div>
  <div className="flex gap-2">{(["bank","executive"] as RateKind[]).map(k => <button key={k} onClick={() => { setKind(k); setImportResult(null); }} className={`rounded-xl px-4 py-2 font-semibold ${kind===k ? "bg-slate-900 text-white" : "border"}`}>{k === "bank" ? "Bank Payout Rates" : "Executive Payout Rates"}</button>)}</div>
  <form onSubmit={e => { e.preventDefault(); void load(); }} className="flex gap-2"><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search rates"/><button className="rounded-xl bg-slate-900 px-4 text-white"><Search size={17}/></button></form>{message && <p className="rounded-xl bg-orange-50 p-3 text-sm text-orange-800">{message}</p>}
  {importResult && <div className="rounded-2xl border bg-white p-4"><p className="font-semibold">Import preview: {importResult.valid_count} valid, {importResult.invalid_count} invalid</p>{importResult.rows.filter(r=>!r.valid).slice(0,10).map(r=><p key={r.row_number} className="mt-1 text-sm text-red-600">Row {r.row_number}: {r.errors.join("; ")}</p>)}<button disabled={!!importResult.invalid_count || !!importResult.imported_count} onClick={() => void confirmImport()} className="mt-3 rounded-xl bg-green-600 px-4 py-2 text-white disabled:opacity-40">Confirm Import</button></div>}
  <div className="overflow-x-auto rounded-2xl border bg-white dark:bg-slate-900"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-900 text-white"><tr>{[kind === "bank" ? "Bank" : "Executive","Bank","City","Loan Type","Product Type","Rate","Effective","Active","Action"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rates.map(r=><tr key={r.id} className="border-b"><td className="p-3 font-medium">{"executive_name" in r ? r.executive_name : r.bank_name}</td><td className="p-3">{"executive_name" in r ? display(r.bank_name) : r.bank_name}</td><td className="p-3">{display(r.city)}</td><td className="p-3">{display(r.loan_type)}</td><td className="p-3">{display(r.product_type)}</td><td className="p-3">₹{Number(r.payout_rate).toFixed(2)}</td><td className="p-3">{r.effective_from} – {r.effective_to || "Open"}</td><td className="p-3"><button onClick={()=>void toggle(r)} className={`rounded-full px-3 py-1 ${r.is_active ? "bg-green-100 text-green-700" : "bg-slate-100"}`}>{r.is_active ? "Active" : "Inactive"}</button></td><td className="p-3"><button onClick={()=>startEdit(r)}><Pencil size={16}/></button></td></tr>)}</tbody></table></div></section>
  {open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">{editing ? "Edit" : "Add"} {kind === "bank" ? "Bank" : "Executive"} Rate</h2><div className="grid gap-4 sm:grid-cols-2">{kind === "executive" && <label>Executive<input list="executive-options" defaultValue={executiveName} required className={input} onChange={e=>setForm({...form, executive_id: executives.find(x=>x.full_name.toLowerCase()===e.target.value.trim().toLowerCase())?.id})}/><datalist id="executive-options">{executives.map(x=><option key={x.id} value={x.full_name}/>)}</datalist></label>}<label>Bank<select className={input} required={kind==="bank"} value={form.bank_id ?? ""} onChange={e=>setForm({...form,bank_id:e.target.value ? Number(e.target.value) : null})}><option value="">All</option>{banks.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>City<input className={input} value={form.city ?? ""} onChange={e=>setForm({...form,city:e.target.value||null})}/></label><label>Loan Type<select className={input} value={form.loan_type ?? ""} onChange={e=>setForm({...form,loan_type:e.target.value||null})}><option value="">All</option>{loans.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label>Product Type<select className={input} value={form.product_type ?? ""} onChange={e=>setForm({...form,product_type:e.target.value||null})}><option value="">All</option>{products.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label>Payout Rate<input required min="0" step="0.01" type="number" className={input} value={form.payout_rate} onChange={e=>setForm({...form,payout_rate:Number(e.target.value)})}/></label><label>Effective From<input required type="date" className={input} value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Effective To<input type="date" className={input} value={form.effective_to ?? ""} onChange={e=>setForm({...form,effective_to:e.target.value||null})}/></label></div><label className="flex gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Active</label><label>Remarks<textarea className={input} value={form.remarks ?? ""} onChange={e=>setForm({...form,remarks:e.target.value||null})}/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2">Cancel</button><button className="rounded-xl bg-orange-600 px-4 py-2 text-white">Save</button></div></form></div>}</DashboardLayout>;
}
