import {Component,useMemo,useState,type ErrorInfo,type ReactNode} from "react";
import * as XLSX from "xlsx";
import {Alert,DataTable,ModalShell} from "../ui";
import {commitCaseImport,previewCases,resumeCaseImport,type ImportPreview,type ImportRow,type ImportState,type MasterOption} from "../../services/caseImportService";

const fields=["los_no","visit_type","company","bank","applicant","mobile","district","city","executive","status"] as const;
const labels:Record<string,string>={los_no:"LOS",visit_type:"Visit Type",company:"Company",bank:"Bank",applicant:"Applicant",mobile:"Mobile",district:"District",city:"City",executive:"Executive",status:"Status"};
const textFields=["los_no","applicant","mobile","address","city","landmark","negative_reason","remarks"];

type Phase="idle"|"selected"|"previewing"|"preview_ready"|"committing"|"success"|"error";
type ModalProps={onClose:()=>void;onImported:()=>Promise<void>};

class ImportErrorBoundary extends Component<{children:ReactNode;onClose:()=>void},{failed:boolean}>{
 state={failed:false};
 static getDerivedStateFromError(){return{failed:true}}
 componentDidCatch(error:Error,info:ErrorInfo){console.error("Case import preview render failed",error,info.componentStack)}
 render(){if(this.state.failed)return <ModalShell title="Import Cases" onClose={this.props.onClose} footer={<><button type="button" onClick={this.props.onClose} className="rounded-xl border px-4 py-2">Close</button><button type="button" onClick={()=>this.setState({failed:false})} className="rounded-xl bg-orange-600 px-4 py-2 text-white">Try Again</button></>}><Alert>Import preview could not be displayed.<br/>Your Excel file has not been imported.</Alert></ModalShell>;return this.props.children}
}

function CaseImportModalContent({onClose,onImported}:ModalProps){
 const[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[phase,setPhase]=useState<Phase>("idle"),[preview,setPreview]=useState<ImportPreview|null>(null),[filter,setFilter]=useState<"ALL"|ImportState>("ALL"),[search,setSearch]=useState(""),[skipped,setSkipped]=useState<Set<number>>(new Set()),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const run=async(task:()=>Promise<ImportPreview|null>)=>{setBusy(true);setPhase("previewing");setError("");try{const next=await task();if(!next){setPhase("idle");setNotice("There is no active import to resume.");return}setPreview(next);setPhase("preview_ready");setNotice("")}catch(e){setPhase("error");setError(e instanceof Error?e.message:"Import preview failed: Unable to load import preview.")}finally{setBusy(false)}};
 const update=(rowNumber:number,field:string,value:string)=>setPreview(current=>current?{...current,rows:current.rows.map(row=>row.row_number===rowNumber?{...row,data:{...row.data,[field]:value}}:row)}:current);
 const companyId=(row:ImportRow)=>preview?.options.companies.find(x=>x.name===row.data.company)?.id;
 const options=(row:ImportRow,field:string):MasterOption[]|string[]=>{
  if(!preview)return[];if(field==="company")return preview.options.companies;if(field==="bank")return preview.options.banks_by_company[String(companyId(row)||"")]||[];
  if(field==="executive")return preview.options.executives;if(field==="district")return preview.options.districts;if(field==="loan_type")return preview.options.loan_types;
  if(field==="visit_type")return preview.options.visit_types;if(field==="status")return preview.options.statuses;return[];
 };
 const visible=useMemo(()=>preview?.rows.filter(row=>(filter==="ALL"||row.state===filter)&&[row.data.los_no,row.data.applicant,row.data.mobile].some(value=>(value||"").toLowerCase().includes(search.toLowerCase())))||[],[preview,filter,search]);
 const commit=async(rows:ImportRow[])=>{if(!preview||!rows.length)return;setBusy(true);setPhase("committing");setError("");try{const result=await commitCaseImport(preview.import_token,rows.filter(row=>!skipped.has(row.row_number)));setNotice(`Imported ${result.imported_rows} rows; ${result.remaining_rows} remain.`);const resumed=await resumeCaseImport();if(resumed)setPreview(resumed);setPhase("success");if(result.imported_rows)await onImported()}catch(e){setPhase("error");setError(e instanceof Error?e.message:"Import failed.")}finally{setBusy(false)}};
 const errorReport=()=>{if(!preview)return;const issues=preview.rows.flatMap(row=>[...row.errors,...row.warnings].map(issue=>({"Row Number":row.row_number,State:row.state,Field:issue.field,Value:issue.entered_value||"",Message:issue.message,Suggestion:issue.suggested_value||""})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(issues),"Import Errors");XLSX.writeFile(wb,"case_import_errors.xlsx")};
 const editor=(row:ImportRow,field:string)=>{
  const choices=options(row,field);const issue=[...row.errors,...row.warnings].find(item=>item.field===field);
  return <div className="min-w-[130px]">{choices.length?<select aria-label={`${labels[field]||field} row ${row.row_number}`} value={row.data[field]||""} disabled={row.state==="IMPORTED"} onChange={e=>{update(row.row_number,field,e.target.value);if(field==="company")update(row.row_number,"bank","")}} className="h-9 w-full rounded-lg border px-2 text-xs"><option value="">Select</option>{choices.map(choice=>{const value=typeof choice==="string"?choice:choice.name;return <option key={value} value={value}>{value}</option>})}</select>:<input aria-label={`${labels[field]||field} row ${row.row_number}`} value={row.data[field]||""} disabled={row.state==="IMPORTED"} onChange={e=>update(row.row_number,field,e.target.value)} className="h-9 w-full rounded-lg border px-2 text-xs"/>}{issue&&<p className={`mt-1 text-[11px] ${row.errors.includes(issue)?"text-red-600":"text-amber-700"}`}>{issue.message}{issue.suggested_value&&<button type="button" className="ml-1 underline" onClick={()=>update(row.row_number,field,issue.suggested_value!)}>Use {issue.suggested_value}</button>}</p>}</div>
 };
 const footer=<><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2">Cancel</button>{preview&&<><button type="button" onClick={errorReport} className="rounded-xl border px-4 py-2">Download Error Report</button><button type="button" disabled={busy} onClick={()=>void commit(preview.rows.filter(row=>row.state==="VALID"||row.state==="WARNING"))} className="rounded-xl bg-orange-600 px-4 py-2 text-white disabled:opacity-50">Import Ready Rows</button><button type="button" disabled={busy} onClick={()=>void commit(preview.rows.filter(row=>row.state!=="IMPORTED"))} className="rounded-xl bg-emerald-700 px-4 py-2 text-white disabled:opacity-50">Import Remaining</button></>}</>;
 return <ModalShell title="Preview & Fix Case Import" subtitle="Correct rows here, then import ready data without reopening Excel." onClose={onClose} footer={footer} className="max-w-[96vw]">
  <div className="space-y-4">{!preview&&<><div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Upload the Case Import workbook. Validation happens before any row is imported.</div><label className="block rounded-xl border border-dashed p-5 text-sm">Choose Excel<input type="file" accept=".xlsx" className="mt-3 block w-full" onChange={e=>{setFile(e.target.files?.[0]||null);setPhase(e.target.files?.[0]?"selected":"idle");setError("")}}/>{file&&<span className="mt-2 block text-slate-500">{file.name}</span>}</label><div className="flex gap-2"><button type="button" disabled={!file||busy} onClick={()=>file&&void run(()=>previewCases(file))} className="rounded-xl bg-orange-600 px-4 py-2 text-white disabled:opacity-50">{phase==="previewing"?"Validating...":"Preview"}</button><button type="button" disabled={busy} onClick={()=>void run(resumeCaseImport)} className="rounded-xl border px-4 py-2">Resume Last Import</button></div></>}
  {error&&<Alert>{error}</Alert>}{notice&&<Alert tone="success">{notice}</Alert>}
  {preview&&<><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold">{preview.filename}</p><p className="text-xs text-slate-500">Uploaded {new Date(preview.uploaded_at).toLocaleString()}</p></div><button className="text-sm underline" onClick={()=>setPreview(null)}>Choose another file</button></div>
  <div className="grid grid-cols-2 gap-2 md:grid-cols-5">{[["Total",preview.summary.total_rows],["Ready",preview.summary.valid_rows],["Warnings",preview.summary.warning_rows],["Errors",preview.summary.error_rows],["Imported",preview.summary.imported_rows]].map(([name,value])=><div className="rounded-xl border p-3" key={name}><p className="text-xs text-slate-500">{name}</p><p className="text-xl font-bold">{value}</p></div>)}</div>
  <div className="flex flex-wrap gap-2">{(["ALL","VALID","WARNING","ERROR","IMPORTED"] as const).map(state=><button key={state} onClick={()=>setFilter(state)} className={`rounded-full border px-3 py-1 text-xs ${filter===state?"bg-slate-900 text-white":""}`}>{state==="ALL"?"All":state==="VALID"?"Ready":state[0]+state.slice(1).toLowerCase()}</button>)}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search LOS, applicant, mobile" className="ml-auto h-9 min-w-64 rounded-lg border px-3 text-sm"/></div>
  <DataTable><table className="min-w-[1700px]"><thead><tr><th>Row</th>{fields.map(field=><th key={field}>{labels[field]}</th>)}<th>Action / Result</th></tr></thead><tbody>{visible.map(row=><tr key={row.row_number} className={skipped.has(row.row_number)?"opacity-40":""}><td>{row.row_number}</td>{fields.map(field=><td key={field}>{editor(row,field)}</td>)}<td className="min-w-56"><p className="font-semibold">{row.state}</p><p className="text-xs">{row.intended_action.replaceAll("_"," ")}</p>{row.state!=="IMPORTED"&&<button type="button" className="mt-2 text-xs underline" onClick={()=>setSkipped(current=>{const next=new Set(current);if(next.has(row.row_number))next.delete(row.row_number);else next.add(row.row_number);return next})}>{skipped.has(row.row_number)?"Restore row":"Skip row"}</button>}<details className="mt-2 text-xs"><summary>More fields</summary>{["loan_type",...textFields.filter(x=>!fields.includes(x as typeof fields[number]))].map(field=><label className="mt-2 block" key={field}>{labels[field]||field.replaceAll("_"," ")}{editor(row,field)}</label>)}</details></td></tr>)}</tbody></table></DataTable></>}</div>
 </ModalShell>;
}

export default function CaseImportModal(props:ModalProps){return <ImportErrorBoundary onClose={props.onClose}><CaseImportModalContent {...props}/></ImportErrorBoundary>}
