import { useEffect, useMemo, useRef, useState } from "react";

export interface MultiSelectItem { id:number; label:string }
export function deduplicateIds(ids:number[]) { return [...new Set(ids)]; }
export function toggleSelectedId(selected:number[], id:number) { return selected.includes(id)?selected.filter(value=>value!==id):deduplicateIds([...selected,id]); }
export function selectionState(selected:number[], visibleIds:number[]) { const set=new Set(selected);const count=visibleIds.filter(id=>set.has(id)).length;return {all:visibleIds.length>0&&count===visibleIds.length,indeterminate:count>0&&count<visibleIds.length}; }
export function selectionSummary(selected:number[],items:MultiSelectItem[],emptyLabel="Select Items") { if(!selected.length)return emptyLabel;if(items.length>0&&selected.length===items.length)return "All Items Selected";if(selected.length===1)return items.find(item=>item.id===selected[0])?.label||"1 Item Selected";return `${selected.length} Items Selected`; }

type Props={items:MultiSelectItem[];selectedIds:number[];onChange:(ids:number[])=>void;selectAllLabel?:string;emptyLabel?:string;disabled?:boolean;searchThreshold?:number;ariaLabel?:string};
export default function MultiSelectCheckboxDropdown({items,selectedIds,onChange,selectAllLabel="Select All",emptyLabel="Select Items",disabled=false,searchThreshold=8,ariaLabel="Select items"}:Props){
 const [open,setOpen]=useState(false);const [search,setSearch]=useState("");const root=useRef<HTMLDivElement>(null);const allRef=useRef<HTMLInputElement>(null);const selected=deduplicateIds(selectedIds);
 const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return term?items.filter(item=>item.label.toLowerCase().includes(term)):items},[items,search]);const visibleIds=filtered.map(item=>item.id);const state=selectionState(selected,visibleIds);
 useEffect(()=>{if(allRef.current)allRef.current.indeterminate=state.indeterminate},[state.indeterminate]);useEffect(()=>{const outside=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("mousedown",outside);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",outside);document.removeEventListener("keydown",key)}},[]);
 const selectVisible=(checked:boolean)=>{const visible=new Set(visibleIds);onChange(checked?deduplicateIds([...selected,...visibleIds]):selected.filter(id=>!visible.has(id)))};
 return <div ref={root} className="relative"><button type="button" disabled={disabled} aria-haspopup="listbox" aria-expanded={open} aria-label={ariaLabel} onClick={()=>setOpen(value=>!value)} className="flex w-full items-center justify-between rounded-xl border bg-white px-3 py-2 text-left disabled:cursor-not-allowed disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900"><span>{selectionSummary(selected,items,emptyLabel)}</span><span aria-hidden>▾</span></button>{open&&!disabled&&<div role="listbox" aria-multiselectable="true" className="absolute z-30 mt-1 max-h-80 w-full min-w-64 overflow-y-auto rounded-xl border bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900">{items.length>=searchThreshold&&<input autoFocus type="search" aria-label="Search items" placeholder="Search…" value={search} onChange={event=>setSearch(event.target.value)} className="mb-2 w-full rounded-lg border px-3 py-2 dark:border-slate-700 dark:bg-slate-950"/>}<div className="flex items-center justify-between"><label className="flex cursor-pointer items-center gap-2 rounded-lg px-3 py-2 font-semibold hover:bg-slate-100 dark:hover:bg-slate-800"><input ref={allRef} type="checkbox" aria-label={search?`${selectAllLabel} Visible`:selectAllLabel} checked={state.all} onChange={event=>selectVisible(event.target.checked)}/>{search?`${selectAllLabel} Visible`:selectAllLabel}</label><button type="button" onClick={()=>onChange([])} className="rounded-lg px-3 py-2 text-sm text-orange-600 hover:bg-orange-50 dark:hover:bg-slate-800">Clear All</button></div><div className="my-1 border-t dark:border-slate-700"/>{filtered.length?filtered.map(item=><label key={item.id} role="option" aria-selected={selected.includes(item.id)} className="flex cursor-pointer items-center gap-2 rounded-lg px-3 py-2 hover:bg-slate-100 dark:hover:bg-slate-800"><input type="checkbox" aria-label={`Select ${item.label}`} checked={selected.includes(item.id)} onChange={()=>onChange(toggleSelectedId(selected,item.id))}/>{item.label}</label>):<p className="px-3 py-4 text-sm text-slate-500">No matching items.</p>}</div>}</div>
}
