import { useEffect, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";
import { createMasterRecord, listMasters, updateMasterRecord } from "../../services/masterService";
import type { Bank, Company, CompanyBank, District } from "../../types/master";

type Tab="companies"|"company-banks"|"districts";
const control="w-full rounded-xl border bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-900";

export default function CompanyMasterPage(){
 const [tab,setTab]=useState<Tab>("companies"); const [companies,setCompanies]=useState<Company[]>([]); const [banks,setBanks]=useState<Bank[]>([]); const [mappings,setMappings]=useState<CompanyBank[]>([]); const [districts,setDistricts]=useState<District[]>([]); const [error,setError]=useState("");
 const [company,setCompany]=useState({name:"",code:"",source_type:"Other" as const,contact_person:"",email:"",mobile:"",is_active:true,remarks:""});
 const [mapping,setMapping]=useState({company_id:0,bank_id:0,is_active:true,remarks:""}); const [district,setDistrict]=useState({name:"",state:"Rajasthan",is_active:true});
 const load=async()=>{try{const [c,b,m,d]=await Promise.all([listMasters("companies",{all:true}),listMasters("banks",{all:true}),listMasters("company-banks",{all:true}),listMasters("districts",{all:true})]);setCompanies(c.items);setBanks(b.items);setMappings(m.items);setDistricts(d.items);setError("")}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load()},[]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();try{if(tab==="companies"){await createMasterRecord("companies",company);setCompany({...company,name:"",code:"",contact_person:"",email:"",mobile:"",remarks:""})}else if(tab==="company-banks"){await createMasterRecord("company-banks",mapping);setMapping({...mapping,bank_id:0,remarks:""})}else{await createMasterRecord("districts",district);setDistrict({...district,name:""})}await load()}catch(err){setError((err as Error).message)}};
 return <DashboardLayout><section className="space-y-5"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-orange-600">Masters</p><h1 className="text-3xl font-bold">Companies, Banks &amp; Districts</h1></div><div className="flex gap-2">{(["companies","company-banks","districts"] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-xl px-4 py-2 ${tab===x?"bg-slate-900 text-white":"border"}`}>{x==="companies"?"Companies / Agencies":x==="company-banks"?"Company-Bank Mapping":"Rajasthan Districts"}</button>)}</div>{error&&<p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
 <form onSubmit={add} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3 dark:border-slate-700 dark:bg-slate-900">{tab==="companies"?<><input required placeholder="Company name" className={control} value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/><input placeholder="Code" className={control} value={company.code} onChange={e=>setCompany({...company,code:e.target.value})}/><select className={control} value={company.source_type} onChange={e=>setCompany({...company,source_type:e.target.value as typeof company.source_type})}>{["WhatsApp","Email","Both","Other"].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Contact person" className={control} value={company.contact_person} onChange={e=>setCompany({...company,contact_person:e.target.value})}/><input type="email" placeholder="Email" className={control} value={company.email} onChange={e=>setCompany({...company,email:e.target.value})}/><input placeholder="Mobile" className={control} value={company.mobile} onChange={e=>setCompany({...company,mobile:e.target.value})}/><input placeholder="Remarks" className={control} value={company.remarks} onChange={e=>setCompany({...company,remarks:e.target.value})}/></>:tab==="company-banks"?<><select required className={control} value={mapping.company_id||""} onChange={e=>setMapping({...mapping,company_id:Number(e.target.value)})}><option value="">Company</option>{companies.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required className={control} value={mapping.bank_id||""} onChange={e=>setMapping({...mapping,bank_id:Number(e.target.value)})}><option value="">Bank</option>{banks.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input placeholder="Remarks" className={control} value={mapping.remarks} onChange={e=>setMapping({...mapping,remarks:e.target.value})}/></>:<><input required placeholder="District name" className={control} value={district.name} onChange={e=>setDistrict({...district,name:e.target.value})}/><input readOnly className={control} value="Rajasthan"/></>}<button className="rounded-xl bg-orange-600 px-4 py-2 text-white">Add</button></form>
 <div className="overflow-x-auto rounded-2xl border bg-white dark:border-slate-700 dark:bg-slate-900"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-900 text-white"><tr>{(tab==="companies"?["NAME","SOURCE","CONTACT","EMAIL","MOBILE","ACTIVE","ACTION"]:tab==="company-banks"?["COMPANY","BANK","ACTIVE","ACTION"]:["DISTRICT","STATE","ACTIVE","ACTION"]).map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{tab==="companies"?companies.map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.name}</td><td className="p-3">{x.source_type}</td><td className="p-3">{x.contact_person||"—"}</td><td className="p-3">{x.email||"—"}</td><td className="p-3">{x.mobile||"—"}</td><td className="p-3">{x.is_active?"Active":"Inactive"}</td><td className="p-3"><button onClick={()=>void updateMasterRecord("companies",x.id,{is_active:!x.is_active}).then(load)} className="text-orange-600">{x.is_active?"Deactivate":"Activate"}</button></td></tr>):tab==="company-banks"?mappings.map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.company_name}</td><td className="p-3">{x.bank_name}</td><td className="p-3">{x.is_active?"Active":"Inactive"}</td><td className="p-3"><button onClick={()=>void updateMasterRecord("company-banks",x.id,{is_active:!x.is_active}).then(load)} className="text-orange-600">{x.is_active?"Deactivate":"Activate"}</button></td></tr>):districts.map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.name}</td><td className="p-3">{x.state}</td><td className="p-3">{x.is_active?"Active":"Inactive"}</td><td className="p-3"><button onClick={()=>void updateMasterRecord("districts",x.id,{is_active:!x.is_active}).then(load)} className="text-orange-600">{x.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></section></DashboardLayout>
}
