import { useCallback, useEffect, useMemo, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";
import { PageHeader } from "../../components/ui";
import { useAuth } from "../../context/AuthContext";
import { listMasters } from "../../services/masterService";
import type { Company, Executive } from "../../types/master";
import { createUser, getUserCompanies, getUserPermissions, listPermissions, listUsers, resetUserPassword, updateUser, updateUserCompanies, updateUserPermissions } from "../../services/userService";
import type { AuthRole, AuthUser, Permission, UserPayload } from "../../types/auth";

const blankUser=():UserPayload=>({full_name:"",username:"",email:"",mobile:"",password:"",role:"Executive",is_active:true,executive_id:null});
const input="w-full rounded-lg border border-slate-300 bg-white p-2.5 text-slate-900 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100";
const defaults:Record<AuthRole,string[]>={Admin:[],Manager:["dashboard.view","cases.view","cases.create","cases.edit","search.view","reports.view","settings.view"],Executive:["dashboard.view","cases.view","cases.edit_assigned","search.view","reports.view_own","settings.view"]};

export default function UsersPage(){
  const {currentUser}=useAuth(); const allowed=(code:string)=>Boolean(currentUser?.permissions.includes(code));
  const canCreate=allowed("users.create"),canEdit=allowed("users.edit"),canDeactivate=allowed("users.deactivate"),canReset=allowed("users.reset_password"),canManage=allowed("users.manage_permissions");
  const [users,setUsers]=useState<AuthUser[]>([]),[executives,setExecutives]=useState<Executive[]>([]),[companies,setCompanies]=useState<Company[]>([]),[catalog,setCatalog]=useState<Permission[]>([]);
  const [form,setForm]=useState<UserPayload>(blankUser),[editingId,setEditingId]=useState<number|null>(null),[selected,setSelected]=useState<Set<string>>(new Set());
  const [search,setSearch]=useState(""),[role,setRole]=useState(""),[active,setActive]=useState(""),[permissionSearch,setPermissionSearch]=useState("");
  const [companySearch,setCompanySearch]=useState(""),[selectedCompanies,setSelectedCompanies]=useState<Set<number>>(new Set());
  const [error,setError]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{setUsers(await listUsers({search:search||undefined,role:role||undefined,is_active:active===""?undefined:active==="active"}));setError("")}catch(e){setError((e as Error).message)}},[search,role,active]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
  useEffect(()=>{if(canCreate||canEdit)void listMasters("executives",{all:true}).then(x=>setExecutives(x.items)).catch(e=>setError((e as Error).message))},[canCreate,canEdit]);
  useEffect(()=>{if(currentUser?.role==="Admin")void listMasters("companies",{all:true}).then(x=>setCompanies(x.items)).catch(e=>setError((e as Error).message))},[currentUser?.role]);
  useEffect(()=>{if(canManage)void listPermissions().then(setCatalog).catch(e=>setError((e as Error).message))},[canManage]);
  const groups=useMemo(()=>Object.entries(catalog.filter(p=>`${p.code} ${p.name} ${p.description}`.toLowerCase().includes(permissionSearch.toLowerCase())).reduce<Record<string,Permission[]>>((all,p)=>{(all[p.module]??=[]).push(p);return all},{})),[catalog,permissionSearch]);
  const visibleCompanies=useMemo(()=>companies.filter(x=>`${x.name} ${x.code||""}`.toLowerCase().includes(companySearch.toLowerCase())),[companies,companySearch]);
  const set=<K extends keyof UserPayload>(key:K,value:UserPayload[K])=>setForm(x=>({...x,[key]:value}));
  const changePermission=(code:string,on:boolean)=>setSelected(current=>{const next=new Set(current);on?next.add(code):next.delete(code);return next});
  const changeModule=(rows:Permission[],on:boolean)=>setSelected(current=>{const next=new Set(current);rows.forEach(p=>on?next.add(p.code):next.delete(p.code));return next});
  async function submit(e:React.FormEvent){e.preventDefault();setError("");setMessage("");try{const payload={...form,executive_id:form.role==="Executive"?form.executive_id:null};const saved=editingId?await updateUser(editingId,payload):await createUser(payload);if(canManage&&form.role!=="Admin")await updateUserPermissions(saved.id,[...selected]);if(currentUser?.role==="Admin"&&form.role!=="Admin")await updateUserCompanies(saved.id,[...selectedCompanies]);setMessage(editingId?"User, permissions, and companies updated.":"User, permissions, and companies created.");setEditingId(null);setForm(blankUser());setSelected(new Set());setSelectedCompanies(new Set());await load()}catch(err){setError((err as Error).message)}}
  async function edit(user:AuthUser){try{setEditingId(user.id);setForm({full_name:user.full_name,username:user.username,email:user.email,mobile:user.mobile||"",role:user.role,is_active:user.is_active,executive_id:user.executive_id});const [codes,assignment]=await Promise.all([canManage?getUserPermissions(user.id):Promise.resolve(user.permissions),currentUser?.role==="Admin"?getUserCompanies(user.id):Promise.resolve({all_companies:false,companies:[]})]);setSelected(new Set(codes));setSelectedCompanies(new Set(assignment.companies.map(x=>x.id)));setError("");setMessage("")}catch(e){setError((e as Error).message)}}
  async function toggle(user:AuthUser){try{await updateUser(user.id,{is_active:!user.is_active});setMessage(`${user.full_name} ${user.is_active?"deactivated":"activated"}.`);await load()}catch(e){setError((e as Error).message)}}
  async function reset(user:AuthUser){const password=window.prompt(`Enter a new strong password for ${user.username}`);if(!password)return;try{await resetUserPassword(user.id,password);setMessage("Password reset successfully.");setError("")}catch(e){setError((e as Error).message)}}
  function startCreate(){setEditingId(0);setForm(blankUser());setSelected(new Set(defaults.Executive));setSelectedCompanies(new Set())}
  return <DashboardLayout><section className="space-y-5 text-slate-900 dark:text-slate-100">
    <PageHeader eyebrow="Administration" title="Users" subtitle="Admin-controlled module and action access." actions={canCreate&&editingId===null?<button onClick={startCreate} className="rounded-lg bg-orange-600 px-4 py-2 text-white">Add User</button>:undefined}/>
    <div className="ui-filter-card md:grid-cols-3"><input aria-label="Search users" className={input} placeholder="Search name, email, username or mobile" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Role filter" className={input} value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{["Admin","Manager","Executive"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Status filter" className={input} value={active} onChange={e=>setActive(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</p>}{message&&<p className="rounded-lg bg-green-50 p-3 text-green-700 dark:bg-green-950/40 dark:text-green-300">{message}</p>}
    {editingId!==null&&(editingId===0?canCreate:canEdit)&&<form onSubmit={submit} className="grid gap-3 rounded-2xl bg-white p-5 shadow dark:bg-slate-900 md:grid-cols-2">
      <h2 className="text-xl font-semibold md:col-span-2">{editingId?"Edit User":"Add User"}</h2><input required className={input} placeholder="Full Name" value={form.full_name} onChange={e=>set("full_name",e.target.value)}/><input required className={input} placeholder="Username" value={form.username} onChange={e=>set("username",e.target.value)}/><input required type="email" className={input} placeholder="Email" value={form.email} onChange={e=>set("email",e.target.value)}/><input required minLength={7} className={input} placeholder="Mobile" value={form.mobile||""} onChange={e=>set("mobile",e.target.value)}/>{!editingId&&<input required type="password" className={input} placeholder="Password (12+ chars, upper/lower/number/symbol)" value={form.password||""} onChange={e=>set("password",e.target.value)}/>}<select className={input} value={form.role} onChange={e=>{const next=e.target.value as AuthRole;setForm(x=>({...x,role:next,executive_id:next==="Executive"?x.executive_id:null}));setSelected(current=>new Set([...current,...defaults[next]]))}}>{["Admin","Manager","Executive"].map(x=><option key={x}>{x}</option>)}</select>{form.role==="Executive"&&<select required className={input} value={form.executive_id||""} onChange={e=>set("executive_id",Number(e.target.value))}><option value="">Link Executive Master</option>{executives.map(x=><option key={x.id} value={x.id}>{x.full_name} ({x.status})</option>)}</select>}<label className="flex items-center gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>set("is_active",e.target.checked)}/> Active</label>
      {currentUser?.role==="Admin"&&<div className="space-y-3 md:col-span-2"><div className="flex justify-between"><h3 className="font-semibold">Assigned Companies</h3><span className="text-sm text-slate-500">{form.role==="Admin"?"All Companies — Full Access":`${selectedCompanies.size} Companies Selected`}</span></div>{form.role!=="Admin"&&<><input className={input} placeholder="Search companies" value={companySearch} onChange={e=>setCompanySearch(e.target.value)}/><div className="flex gap-3 text-xs"><button type="button" onClick={()=>setSelectedCompanies(current=>new Set([...current,...visibleCompanies.map(x=>x.id)]))} className="text-orange-600">Select All Visible</button><button type="button" onClick={()=>setSelectedCompanies(current=>{const next=new Set(current);visibleCompanies.forEach(x=>next.delete(x.id));return next})} className="text-slate-500">Clear All</button></div><div className="grid max-h-56 gap-2 overflow-y-auto rounded-xl border p-3 dark:border-slate-700 md:grid-cols-2">{visibleCompanies.map(company=><label key={company.id} className="flex gap-2"><input type="checkbox" checked={selectedCompanies.has(company.id)} onChange={e=>setSelectedCompanies(current=>{const next=new Set(current);e.target.checked?next.add(company.id):next.delete(company.id);return next})}/><span>{company.name}{company.code?` (${company.code})`:""}</span></label>)}</div>{selectedCompanies.size===0&&<p className="text-sm text-amber-600">No companies assigned. This user will have no company data access.</p>}</>}</div>}
      {canManage&&<div className="space-y-3 md:col-span-2"><div className="flex justify-between"><h3 className="font-semibold">Permissions</h3><span className="text-sm text-slate-500">{form.role==="Admin"?catalog.length:selected.size} permissions granted</span></div><input className={input} placeholder="Search permissions" value={permissionSearch} onChange={e=>setPermissionSearch(e.target.value)}/>{groups.map(([module,rows])=><fieldset key={module} className="rounded-xl border p-3 dark:border-slate-700"><legend className="px-2 font-semibold">{module}</legend><div className="mb-2 flex gap-3 text-xs"><button type="button" disabled={form.role==="Admin"} onClick={()=>changeModule(rows,true)} className="text-orange-600">Select All</button><button type="button" disabled={form.role==="Admin"} onClick={()=>changeModule(rows,false)} className="text-slate-500">Clear All</button></div><div className="grid gap-2 md:grid-cols-2">{rows.map(p=><label key={p.code} className="flex gap-2 rounded-lg p-2 hover:bg-slate-50 dark:hover:bg-slate-800"><input type="checkbox" disabled={form.role==="Admin"} checked={form.role==="Admin"||selected.has(p.code)} onChange={e=>changePermission(p.code,e.target.checked)}/><span><span className="block text-sm font-medium">{p.name}</span><span className="block text-xs text-slate-500">{p.code}</span></span></label>)}</div></fieldset>)}</div>}
      <div className="flex gap-2 md:col-span-2"><button className="rounded-lg bg-orange-600 px-4 py-2 text-white">Save User &amp; Permissions</button><button type="button" onClick={()=>{setEditingId(null);setForm(blankUser())}} className="rounded-lg border px-4 py-2">Cancel</button></div>
    </form>}
    <div className="overflow-x-auto rounded-2xl bg-white shadow dark:bg-slate-900"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-100 dark:bg-slate-800"><tr>{["Full Name","Email / Username","Mobile","Role","Executive Link","Access","Status","Created","Last Login","Actions"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-slate-200 dark:border-slate-800"><td className="p-3 font-medium">{user.full_name}</td><td className="p-3">{user.email}<div className="text-slate-500">{user.username}</div></td><td className="p-3">{user.mobile||"—"}</td><td className="p-3">{user.role}</td><td className="p-3">{user.executive_name||"—"}</td><td className="p-3">{user.permissions.length} permissions granted</td><td className="p-3">{user.is_active?"Active":"Inactive"}</td><td className="p-3">{new Date(user.created_at).toLocaleString()}</td><td className="p-3">{user.last_login?new Date(user.last_login).toLocaleString():"Never"}</td><td className="p-3 whitespace-nowrap">{canEdit&&<button onClick={()=>void edit(user)} className="mr-3 text-orange-700">Edit</button>}{canDeactivate&&<button onClick={()=>void toggle(user)} className="mr-3 text-blue-700">{user.is_active?"Deactivate":"Activate"}</button>}{canReset&&<button onClick={()=>void reset(user)} className="text-slate-700 dark:text-slate-300">Reset Password</button>}{!canEdit&&!canDeactivate&&!canReset&&"View only"}</td></tr>)}</tbody></table></div>
  </section></DashboardLayout>;
}
